update showheroes docs
showheroes/prebid.github.io pull request #1
Opened 2024-08-20 14:21 UTC by FilipStamenkovic

## 🏷 Type of documentation

- [x] update bid adapter

## 📋 Checklist

- [x] Related pull requests in prebid.js or server are linked -> https://github.com/showheroes/Prebid.js/pull/4

2024-08-22 13:00 UTC, musikele approved these changes
LGTM

2024-09-19 13:58 UTC, musikele requested changes
remove qa.pageURL

2024-09-19 13:58 UTC, musikele commented on dev-docs/bidders/showheroes-bs.md
> +                    "pageURL": "https://testing.domain.com/"
this is not needed anymore

2024-09-19 13:58 UTC, musikele commented on dev-docs/bidders/showheroes-bs.md
> +                  "pageURL": "https://dev-pagetests.viralize.com/"
not needed

2024-09-23 13:12 UTC, musikele approved these changes
LGTM

2024-09-24 07:25 UTC, francesconistri commented on dev-docs/bidders/showheroes-bs.md
> +                }
In my opinion we should provide a specific param for testing (like `testing: true` or `preview: true`), instead of using `qa`.
For our publishers, changing the endpoint does not make much sense.

2024-09-24 07:25 UTC, francesconistri commented on dev-docs/bidders/showheroes-bs.md
> +];
We are suggesting our publishers to use appnexus' rendererer.

Are we receiving all the events from the creative?

2024-09-24 07:25 UTC, francesconistri commented on dev-docs/bidders/showheroes-bs.md
> +| `unitId`    | required                         | Monetize unit ID                    | `'AACBTwsZVANd9NlB'`                     | `string`  |
Actually our product is now called ShowHeroes MAX

2024-09-24 07:25 UTC, francesconistri commented on dev-docs/bidders/showheroes-bs.md
> +                qa: {
This is the public documentation, do we really want to expose our QA params?

2024-09-24 07:25 UTC, francesconistri commented on dev-docs/bidders/showheroes-bs.md
> +                unitId: "AACBTwsZVANd9NlB",
Developers will use these parameters to test their config.
Here some open questions coming to my mind:

What unit id are we using here ? 
Do we have a generic test unit created on our platform, that will be used during the integrations implementation?
Is our analytics tracking those test requests, or completely discarding it?

2024-09-24 07:25 UTC, francesconistri commented on dev-docs/bidders/showheroes-bs.md
> +              qa: {
See previous comment.

2024-09-24 07:25 UTC, francesconistri commented on dev-docs/bidders/showheroes-bs.md
> +              unitId: "AAFo8FVWXycNdR8K",
See previous comment.

2024-09-24 08:05 UTC, francesconistri commented on dev-docs/bidders/showheroes-bs.md
> +                unitId: "AACBTwsZVANd9NlB",
As discussed privately, we now provide fake zid.

When using the preview mode, a test ad will be returned, even if the zid is not valid.
No tracking will be performed on analytics.

When the developer will remove the preview mode, the bidder will stop returning any bids.

2024-09-24 08:10 UTC, francesconistri approved these changes

2024-09-30 13:23 UTC, FilipStamenkovic commented
Official PR opened: https://github.com/prebid/prebid.github.io/pull/5627

2024-09-30 13:23 UTC, closed without merging